services:
  nats-servers:
    image: nats:latest
    ports:
      - "4222:4222"
      - "8222:8222"

  auth-db:
    image: postgres:latest
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres_auth
      - POSTGRES_PASSWORD=336366!Auth
      - POSTGRES_DB=authdb
    volumes:
      - ./database/auth-ms/postgres:/var/lib/postgresql/data
    restart: always

  product-db:
    image: postgres:latest
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER_PRODUCTS_ENV}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD_PRODUCTS_ENV}
      - POSTGRES_DB=${POSTGRES_DB_PRODUCTS_ENV}
    volumes:
      - ./database/products-ms/postgres:/var/lib/postgresql/data
    restart: always

  branches-db:
    image: postgres:latest
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER_BRANCHES_ENV}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD_BRANCHES_ENV}
      - POSTGRES_DB=${POSTGRES_DB_BRANCHES_ENV}
    volumes:
      - ./database/branch-ms/postgres:/var/lib/postgresql/data
    restart: always

  contacts-db:
    image: postgres:latest
    ports:
      - "5436:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER_CONTACTS_ENV}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD_CONTACTS_ENV}
      - POSTGRES_DB=${POSTGRES_DB_CONTACTS_ENV}
    volumes:
      - ./database/contacts-ms/postgres:/var/lib/postgresql/data
    restart: always

  voucher-db:
    image: postgres:latest
    ports:
      - "5437:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER_VOUCHER_ENV}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD_VOUCHER_ENV}
      - POSTGRES_DB=${POSTGRES_DB_VOUCHER_ENV}
    volumes:
      - ./database/voucher-ms/postgres:/var/lib/postgresql/data
    restart: always
