name: Build and Push Docker Images

on:
  push:
    paths:
      - "client-gateway/**"
      - "frontend/**"
      - "microservices/auth-ms/**"
      - "microservices/branches-ms/**"
      - "microservices/contacts-ms/**"
      - "microservices/products-ms/**"
      - "microservices/voucher-ms/**"
    branches:
      - main # o master, según tu repositorio

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service:
          - client-gateway
          - frontend
          - microservices/auth-ms
          - microservices/branches-ms
          - microservices/contacts-ms
          - microservices/products-ms
          - microservices/voucher-ms

    steps:
      - name: Checkout main repo with submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.service }}
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.service }}:latest
